-- WEB NIXO ACADEMY - SUPABASE DATABASE SETUP SQL
-- Execute this in your Supabase SQL Editor

-- 1. Create registrations table
CREATE TABLE IF NOT EXISTS public.registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone_number TEXT,
    login_id TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    university TEXT,
    course_id TEXT NOT NULL,
    course_title TEXT NOT NULL,
    amount NUMERIC,
    payment_method TEXT,
    payment_id TEXT,
    certificate_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create course_settings table
CREATE TABLE IF NOT EXISTS public.course_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id TEXT UNIQUE NOT NULL,
    price NUMERIC NOT NULL,
    is_live BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create coupons table
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount NUMERIC NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create global_settings table
CREATE TABLE IF NOT EXISTS public.global_settings (
    id TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.global_settings ENABLE ROW LEVEL SECURITY;

-- 6. Create Policies (Idempotent)

-- Registrations
DROP POLICY IF EXISTS "Enable insert for all" ON public.registrations;
CREATE POLICY "Enable insert for all" ON public.registrations FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable read for all" ON public.registrations;
CREATE POLICY "Enable read for all" ON public.registrations FOR SELECT USING (true); -- Note: In production, restrict this to admin only

-- Course Settings
DROP POLICY IF EXISTS "Enable read for all settings" ON public.course_settings;
CREATE POLICY "Enable read for all settings" ON public.course_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable all for all settings" ON public.course_settings;
CREATE POLICY "Enable all for all settings" ON public.course_settings FOR ALL USING (true);

-- Coupons
DROP POLICY IF EXISTS "Enable read for all coupons" ON public.coupons;
CREATE POLICY "Enable read for all coupons" ON public.coupons FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable all for all coupons" ON public.coupons;
CREATE POLICY "Enable all for all coupons" ON public.coupons FOR ALL USING (true);

-- Global Settings
DROP POLICY IF EXISTS "Enable read for all global settings" ON public.global_settings;
CREATE POLICY "Enable read for all global settings" ON public.global_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable all for all global settings" ON public.global_settings;
CREATE POLICY "Enable all for all global settings" ON public.global_settings FOR ALL USING (true);
