-- WEB NIXO ACADEMY - SUPABASE DATABASE SETUP SQL
-- Execute this in your Supabase SQL Editor

-- 1. Create registrations table
CREATE TABLE IF NOT EXISTS public.registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone_number TEXT,
    login_id TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    university TEXT,
    course_id TEXT NOT NULL,
    course_title TEXT NOT NULL,
    amount NUMERIC,
    payment_method TEXT,
    payment_id TEXT,
    certificate_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create course_settings table
CREATE TABLE IF NOT EXISTS public.course_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id TEXT UNIQUE NOT NULL,
    price NUMERIC NOT NULL,
    is_live BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create coupons table
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount NUMERIC NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies

-- Registrations: Anyone can insert (sign up), only authenticated users can read (or you can restrict to admin)
CREATE POLICY "Enable insert for all" ON public.registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for all" ON public.registrations FOR SELECT USING (true); -- Note: In production, restrict this to admin only

-- Course Settings: Anyone can read, only admin can update (for this demo, we allow all for simplicity)
CREATE POLICY "Enable read for all settings" ON public.course_settings FOR SELECT USING (true);
CREATE POLICY "Enable all for all settings" ON public.course_settings FOR ALL USING (true);

-- Coupons: Anyone can read, only admin can update
CREATE POLICY "Enable read for all coupons" ON public.coupons FOR SELECT USING (true);
CREATE POLICY "Enable all for all coupons" ON public.coupons FOR ALL USING (true);
